import React from 'react';
import { Container, Typography, Accordion, AccordionSummary, AccordionDetails } from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

const Docs = () => {
  return (
    <Container>
      <Typography variant="h4" component="h1" gutterBottom>
        Documentation
      </Typography>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="h6">Bot Info</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Our trading bots use advanced algorithms to analyze market conditions and execute trades on your behalf. Each bot is designed with a specific trading strategy in mind, whether it be conservative, aggressive, or balanced.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="h6">Fees</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            We charge a small percentage fee on profits generated by our bots. There are no hidden fees, and you only pay when you profit. Detailed information on our fee structure can be found in your account settings.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="h6">Opt In and Opt Out</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            You can opt-in to use our trading bots at any time. Similarly, you can opt-out and stop using the bots whenever you wish. Note that any active trades will need to be closed before fully opting out.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="h6">Changing Money Between Bots</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            You can reallocate your funds between different bots to adjust your investment strategy. This can be done from the portfolio management section of your account. Changes will take effect at the next trading session.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="h6">Withdrawals and Deposits</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Deposits and withdrawals can be made at any time. Please note that withdrawals might take up to 3 business days to process due to banking regulations. Ensure your bank details are up-to-date in your account settings.
          </Typography>
        </AccordionDetails>
      </Accordion>
    </Container>
  );
};

export default Docs;
